In [34]:
import numpy as np 
import pandas as pd

In [64]:
date=pd.read_csv('order.csv')
time=pd.read_csv(r"C:\Users\priya\OneDrive\manisha\messages (1).csv")

In [65]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [67]:
date['date']=pd.to_datetime(date['date'])
time['date']=pd.to_datetime(time['date'])
date.head()
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        20 non-null     datetime64[us]
 1   product_id  20 non-null     int64
 2   city_id     20 non-null     int64
 3   orders      20 non-null     int64
dtypes: datetime64[us](1), int64(3)
memory usage: 772.0 bytes

In [68]:
date['day_oftheweek_date']=date['date'].dt.dayofweek
date.head()

        date  product_id  city_id  orders  day_oftheweek_date
0 2019-12-10        5628       25       3                   1
1 2018-08-15        3646       14     157                   2
2 2018-10-23        1859       25       1                   1
3 2019-08-17        7292       25       1                   5
4 2019-01-06        4344       25       3                   6

In [69]:
date['day_name']=date['date'].dt.day_name()

In [70]:
date.head()

        date  product_id  city_id  orders  day_oftheweek_date   day_name
0 2019-12-10        5628       25       3                   1    Tuesday
1 2018-08-15        3646       14     157                   2  Wednesday
2 2018-10-23        1859       25       1                   1    Tuesday
3 2019-08-17        7292       25       1                   5   Saturday
4 2019-01-06        4344       25       3                   6     Sunday

In [71]:
date['date_is_wknd']=np.where(date['day_name'].isin(['Sunday','Saturday']),1,0)

In [72]:
date.head()

,date,product_id,city_id,orders,day_oftheweek_date,day_name,date_is_wknd
0,2019-12-10,5628,25,3,1,Tuesday,0
1,2018-08-15,3646,14,157,2,Wednesday,0
2,2018-10-23,1859,25,1,1,Tuesday,0
3,2019-08-17,7292,25,1,5,Saturday,1
4,2019-01-06,4344,25,3,6,Sunday,1

In [73]:
date['no_of_week_in_year'] = date['date'].dt.isocalendar().week

In [74]:
date.head()

,date,product_id,city_id,orders,day_oftheweek_date,day_name,date_is_wknd,no_of_week_in_year
0,2019-12-10,5628,25,3,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2,Wednesday,0,33
2,2018-10-23,1859,25,1,1,Tuesday,0,43
3,2019-08-17,7292,25,1,5,Saturday,1,33
4,2019-01-06,4344,25,3,6,Sunday,1,1

In [75]:
import datetime
today=datetime.datetime.today()

In [76]:
np.round((today-date['date'])/np.timedelta64(30,'D'))

0      80.0
1      96.0
2      93.0
3      83.0
4      91.0
5      88.0
6      93.0
7      85.0
8      98.0
9      82.0
10     98.0
11     81.0
12     91.0
13     88.0
14     95.0
15     86.0
16     97.0
17     82.0
18    100.0
19     89.0
Name: date, dtype: float64

In [77]:
time.head()
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [78]:
(today-time['date']).dt.days

0      4574
1      4439
2      4924
3      4226
4      4624
       ...
995    5213
996    4535
997    5000
998    5116
999    4388
Name: date, Length: 1000, dtype: int64

In [61]:
time.info()

<class 'pandas.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: date
Non-Null Count  Dtype
--------------  -----
20 non-null     datetime64[us]
dtypes: datetime64[us](1)
memory usage: 292.0 bytes