In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv("OHE.csv")

In [3]:
df

    Name  Gender       City  Color
0   Aman    Male      Delhi    Red
1  Priya  Female     Mumbai   Blue
2  Rohan    Male      Delhi  Green
3  Sneha  Female  Bangalore    Red
4  Arjun    Male     Mumbai   Blue
5  Kavya  Female    Chennai  Green
6  Rahul    Male  Bangalore   Blue
7   Neha  Female      Delhi    Red

In [4]:
Ohe_p=pd.get_dummies(df,columns=['Gender','City','Color'])

In [5]:
Ohe_p

,Name,Gender_Female,Gender_Male,City_Bangalore,City_Chennai,City_Delhi,City_Mumbai,Color_Blue,Color_Green,Color_Red
0,Aman,False,True,False,False,True,False,False,False,True
1,Priya,True,False,False,False,False,True,True,False,False
2,Rohan,False,True,False,False,True,False,False,True,False
3,Sneha,True,False,True,False,False,False,False,False,True
4,Arjun,False,True,False,False,False,True,True,False,False
5,Kavya,True,False,False,True,False,False,False,True,False
6,Rahul,False,True,True,False,False,False,True,False,False
7,Neha,True,False,False,False,True,False,False,False,True

In [18]:
#**VIA SICK-IT LEARN**
from sklearn.preprocessing import OneHotEncoder

In [7]:
sd = OneHotEncoder(sparse_output=False)

In [8]:
sd_data = sd.fit_transform(df[['Gender', 'City', 'Color']])

In [9]:
sd_data

array([[0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.]])

In [10]:
encoded_cols = sd.get_feature_names_out(['Gender', 'City', 'Color'])

In [11]:
encoded_cols

array(['Gender_Female', 'Gender_Male', 'City_Bangalore', 'City_Chennai',
       'City_Delhi', 'City_Mumbai', 'Color_Blue', 'Color_Green',
       'Color_Red'], dtype=object)

In [12]:
print(sd_data.shape)
print(len(encoded_cols))

(8, 9)
9

In [13]:
encoded_df = pd.DataFrame(sd_data, columns=encoded_cols)

final_df = pd.concat([df[['Name']], encoded_df], axis=1)

print(final_df)

    Name  Gender_Female  Gender_Male  City_Bangalore  City_Chennai  \
0   Aman            0.0          1.0             0.0           0.0
1  Priya            1.0          0.0             0.0           0.0
2  Rohan            0.0          1.0             0.0           0.0
3  Sneha            1.0          0.0             1.0           0.0
4  Arjun            0.0          1.0             0.0           0.0
5  Kavya            1.0          0.0             0.0           1.0
6  Rahul            0.0          1.0             1.0           0.0
7   Neha            1.0          0.0             0.0           0.0

   City_Delhi  City_Mumbai  Color_Blue  Color_Green  Color_Red
0         1.0          0.0         0.0          0.0        1.0
1         0.0          1.0         1.0          0.0        0.0
2         1.0          0.0         0.0          1.0        0.0
3         0.0          0.0         0.0          0.0        1.0
4         0.0          1.0         1.0          0.0        0.0
5         0.0          0.0         0.0          1.0        0.0
6         0.0          0.0         1.0          0.0        0.0
7         1.0          0.0         0.0          0.0        1.0

In [14]:
print(df.columns)
print(sd_data.shape)

Index(['Name', 'Gender', 'City', 'Color'], dtype='str')
(8, 9)

In [15]:
print(len(encoded_cols))
print(encoded_cols)

9
['Gender_Female' 'Gender_Male' 'City_Bangalore' 'City_Chennai'
 'City_Delhi' 'City_Mumbai' 'Color_Blue' 'Color_Green' 'Color_Red']